# What is PyTorch?
> It’s a Python based scientific computing package targeted at two sets of audiences:
<br>
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed

### Tensors
> Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [3]:
import torch
from __future__ import print_function

In [6]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000,  2.0000,  0.0000],
        [ 2.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [7]:
# Construct a randomly initialized matrix:
x = torch.rand(5,3)
print(x)

tensor([[ 0.5632,  0.6821,  0.0376],
        [ 0.0364,  0.8399,  0.9063],
        [ 0.0441,  0.1697,  0.4060],
        [ 0.7109,  0.8725,  0.1978],
        [ 0.8611,  0.5952,  0.9767]])


In [8]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [9]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-0.1742,  0.7028,  0.0842],
        [ 1.1101,  0.4121, -1.8247],
        [-0.6708, -1.4913, -0.1259],
        [-0.5003, -1.3526,  0.8608],
        [ 0.4035,  0.5622, -0.3298]])


In [11]:
print(x.size())

torch.Size([5, 3])


### Operations

In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1134,  1.3469,  0.9869],
        [ 2.0264,  0.8872, -1.6563],
        [-0.4458, -0.8965,  0.6901],
        [ 0.1984, -1.2110,  1.3296],
        [ 0.8717,  0.6438,  0.2588]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.1134,  1.3469,  0.9869],
        [ 2.0264,  0.8872, -1.6563],
        [-0.4458, -0.8965,  0.6901],
        [ 0.1984, -1.2110,  1.3296],
        [ 0.8717,  0.6438,  0.2588]])


In [14]:
# Addition: in-place

# adds x to y
y.add_(x)
print(y)

tensor([[ 0.1134,  1.3469,  0.9869],
        [ 2.0264,  0.8872, -1.6563],
        [-0.4458, -0.8965,  0.6901],
        [ 0.1984, -1.2110,  1.3296],
        [ 0.8717,  0.6438,  0.2588]])


In [15]:
print(x[:, 1])

tensor([ 0.7028,  0.4121, -1.4913, -1.3526,  0.5622])


In [16]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2170])
-0.2170364260673523


### NumPy Bridge

In [19]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


### Autograd: automatic differentiation

In [24]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [25]:
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [26]:
print(y.grad_fn)

In [27]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [28]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [29]:
out.backward()

In [30]:
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])
