### 1. Import the numpy package under the name np

In [3]:
import numpy as np

### 2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
np.show_config()

1.14.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]


### 3. Create a null vector of size 10

In [6]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [9]:
Z = np.zeros((10,10))
print(Z.size,Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

100 8
800 bytes


### 5. How to get the documentation of the numpy add function from the command line?

In [10]:
%run `python -c "import numpy; numpy.info(numpy.add)"

ERROR:root:File `'`python.py'` not found.


### 6. Create a null vector of size 10 but the fifth value which is 1

In [11]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [12]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last)

In [13]:
Z = np.arange(20)
Z = Z[::-1]
print(Z)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
Z = np.arange(9).reshape((-1,3))
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [17]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


### 11. Create a 3x3 identity matrix

In [18]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values

In [19]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.77467286 0.13554305 0.17857636]
  [0.07158621 0.87152042 0.43019985]
  [0.20164858 0.49161847 0.23617808]]

 [[0.84741318 0.46994818 0.85615842]
  [0.96523869 0.52126829 0.68015802]
  [0.66429555 0.23044742 0.61051932]]

 [[0.42350556 0.64097345 0.47539791]
  [0.22820719 0.56893716 0.68285531]
  [0.99246042 0.13508219 0.93589564]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
Z = np.random.random((10,10))
print(Z.min(),Z.max())

0.0622188203507833 0.9832126654310235


### 14. Create a random vector of size 30 and find the mean value

In [21]:
Z = np.random.random((30))
print(Z.mean())

0.517327220016256


### 15. Create a 2d array with 1 on the border and 0 inside

In [23]:
Z = np.ones((4,4))
Z[1:-1,1:-1]= 0
print(Z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [24]:
Z = np.ones((5,5))
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression?

In [25]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [26]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [27]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


# Source: <a href="https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md">Link</a>